version: "3.9"

services:
  postgres:
    image: postgres:15
    platform: linux/amd64
    environment:
      POSTGRES_DB: schema_registry
      POSTGRES_USER: sr
      POSTGRES_PASSWORD: sr
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  schema-registry:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/schema_registry
      SPRING_DATASOURCE_USERNAME: sr
      SPRING_DATASOURCE_PASSWORD: sr

volumes:
  pgdata:
